services:
  - type: web
    name: air-quality-app
    env: python
    plan: free
    buildCommand: |
      apt-get update && apt-get install -y chromium chromium-driver
      pip install -r requirements.txt
    startCommand: streamlit run Deploy.py --server.port $PORT --server.enableCORS false
